from new_dataset import PAD_TOKEN, START_TOKEN, END_TOKEN, MAX_LEN, VOCAB_SIZE
PAD = PAD_TOKEN
UNK = -1
BOS = START_TOKEN
EOS = END_TOKEN

PAD_WORD = '<blank>'
UNK_WORD = '<unk>'
BOS_WORD = '<s>'
EOS_WORD = '</s>'
